version: "3.1"

services:
  
  mongobase:
    build:
      context: ./Database
    restart: unless-stopped
    command: mongod --bind_ip_all

  mongo-seed:
    build:
      context: ./Database
      dockerfile: ./Seed.Dockerfile
    links:
      - mongobase

  api:
    build:
      context: ./Back-end/
    ports:
      - "8080:8080"
    depends_on:
      - mongobase

  frontend:
    build:
      context: ./Front-end/
    ports:
      - "8081:80"
    depends_on:
      - api